---
  extends:
    - airbnb
    - eslint:recommended
    - prettier
    - prettier/flowtype
    - prettier/react
    - plugin:import/react
    - plugin:import/recommended
    - plugin:flowtype/recommended
    - plugin:react/recommended

  env:
    browser: true
    node: true
    es6: true

  parser: "babel-eslint"
  parserOptions:
    ecmaVersion: 6
    sourceType: "module"
    ecmaFeatures:
      arrowFunctions: true
      binaryLiterals: true
      blockBindings: true
      classes: true
      defaultParams: true
      destructuring: true
      forOf: true
      generators: true
      modules: true
      objectLiteralComputedProperties: true
      objectLiteralDuplicateProperties: true
      objectLiteralShorthandMethods: true
      objectLiteralShorthandProperties: true
      octalLiterals: true
      regexUFlag: true
      regexYFlag: true
      spread: true
      superInFunctions: true
      templateStrings: true
      unicodeCodePointEscapes: true
      globalReturn: true
      jsx: true
      experimentalObjectRestSpread: true

  globals:
    __DEV__: true
    __SERVER__: true

  plugins:
    - react
    - promise
    - prettier
    - flowtype
    - import

  rules:
    # prettier/prettier: "error"

    react/destructuring-assignment: 0
    react/display-name: 1
    react/jsx-filename-extension: 0
    react/jsx-no-duplicate-props: [1, { ignoreCase: true }]
    react/jsx-no-undef: 1
    react/jsx-pascal-case: 1
    react/jsx-props-no-spreading: 0
    react/jsx-sort-props: 1
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
    react/no-deprecated: 1
    react/no-direct-mutation-state: 1
    react/no-find-dom-node: 1
    react/no-is-mounted: 1
    react/no-render-return-value: 1
    react/no-unknown-property: 1
    react/no-unused-prop-types: 0
    react/prefer-es6-class: [1, "always"]
    react/prop-types: 0
    react/react-in-jsx-scope: 1
    react/require-default-props: 0
    react/require-render-return: 1
    react/self-closing-comp: 1
    react/sort-comp: [1, {
      order: [
        "everything-else",
        "instance-variables",
        "static-methods",
        "lifecycle",
        "instance-methods",
        "render"
      ],
    }]
    react/sort-prop-types: 1
    react/state-in-constructor: 0
    react/static-property-placement: 0
    react/style-prop-object: 1
    react/default-props-match-prop-types: 0
    jsx-a11y/click-events-have-key-events: 0
    jsx-a11y/label-has-associated-control: 0
    jsx-a11y/label-has-for: 0
    jsx-a11y/media-has-caption: 0
    jsx-a11y/no-static-element-interactions: 0
    jsx-a11y/no-noninteractive-element-interactions: 0
    jsx-a11y/tabindex-no-positive: 0

    max-len: ["warn", { code: 150 }]

    semi: 0
    key-spacing: 1
    curly: 0
    consistent-return: 0
    space-infix-ops: 1
    camelcase: 0
    no-spaced-func: 1
    no-alert: 1
    eol-last: 1
    comma-spacing: 1
    eqeqeq: 1

    # possible errors
    comma-dangle: 0
    no-cond-assign: 2
    no-console: 0
    no-constant-condition: 2
    no-control-regex: 2
    no-debugger: 2
    no-dupe-args: 2
    no-dupe-keys: 2
    no-duplicate-case: 2
    no-empty-character-class: 2
    no-empty: 2
    no-ex-assign: 2
    no-extra-boolean-cast: 2
    no-extra-parens: 0
    no-extra-semi: 2
    no-func-assign: 2
    no-inner-declarations: 2
    no-invalid-regexp: 2
    no-irregular-whitespace: 2
    no-negated-in-lhs: 2
    no-obj-calls: 2
    no-param-reassign: 0
    no-plusplus: 0
    no-regex-spaces: 2
    no-sparse-arrays: 2
    no-unexpected-multiline: 2
    no-unreachable: 2
    use-isnan: 2
    valid-jsdoc: 2
    valid-typeof: 2

    no-redeclare: 2

    init-declarations: 2
    no-catch-shadow: 2
    no-delete-var: 2
    no-label-var: 2
    no-shadow-restricted-names: 2
    no-shadow: 2
    no-undef-init: 2
    no-undef: 2
    no-undefined: 0
    no-unused-vars: ["error", { args: "after-used" }]
    no-use-before-define: 2
    lines-between-class-members: off
    no-underscore-dangle: 0

    import/extensions: 0
    import/no-extraneous-dependencies: 0

    array-element-newline: off
    array-bracket-newline: off
    object-curly-newline: off
